### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by Maytha8** [elliotwutingfeng/asciiset#5]
According to CREDITS.md, some code is sourced from a project licensed under BSD-2-Clause, but does not specify which. Could you please clarify which file(s) contain this code, and whether they are multilicensed under both BSD-3-Clause and BSD-2-Clause?

Thanks,
Maytham

**Comment by elliotwutingfeng** [comment]
Hi,

As stated by CREDITS.md https://github.com/yourbasic/bit is licensed under the BSD 2 Clause license, while the Go language source (from which some of the code is used to make asciiset) is under the BSD 3 Clause license.

This entire project itself is under the BSD 3 Clause license.

If you redistribute this project (whether in source or binary form), you will have to include all 3 aforementioned license notices and their copyright statements.
